SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://shortener:123456@localhost/shortener'
SQLALCHEMY_ECHO = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
CSRF_ENABLED = True
SECRET_KEY = "xckdfuhaskdhihnlqkCDHKLruqILH"
DEBUG = True
SERVER_NAME = '127.0.0.1:5000'